from flask import Blueprint, request, jsonify
from app.controllers.employee_controller import EmployeeController

# Generated by Copilot

# Create a Blueprint for employee routes
employee_routes = Blueprint('employee_routes', __name__)

# Initialize the EmployeeController
employee_controller = EmployeeController()

# Route to list all employees
@employee_routes.route('/employees', methods=['GET'])
def list_employees():
    """Retrieve a list of all employees."""
    employees = employee_controller.list_employees()  # Corrected method call
    return jsonify(employees), 200

# Route to add a new employee
@employee_routes.route('/employees', methods=['POST'])
def add_employee():
    """Add a new employee to the system."""
    data = request.get_json()
    new_employee = employee_controller.add_employee(data)
    return jsonify(new_employee), 201

# Route to delete an employee by ID
@employee_routes.route('/employees/<int:id>', methods=['DELETE'])
def delete_employee(id):
    """Delete an employee by their unique ID."""
    employee_controller.delete_employee(id)
    return jsonify({'message': 'Employee deleted successfully'}), 204

# Route to update an employee by ID
@employee_routes.route('/employees/<int:id>', methods=['PUT'])
def update_employee(id):
    """Update an existing employee's information by their unique ID."""
    data = request.get_json()
    updated_employee = employee_controller.update_employee(id, data)
    return jsonify(updated_employee), 200

# Route to get employees sorted by last name
@employee_routes.route('/employees/sorted-by-last-name', methods=['GET'])
def get_sorted_employees_by_last_name():
    """Retrieve a list of employees sorted by their last name."""
    sorted_employees = employee_controller.getSortedEmployeesByLastName()
    return jsonify(sorted_employees), 200